# configs/config.yaml
environment: development
server:
  port: ":8080"
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "12321"
  db_name: "oolio-order-service"
  sslmode: "disable"
  max_conns: 10
  min_conns: 5
  conn_max_lifetime: 5m
testdb:
  host: "localhost"
  port: 5433
  user: "user"
  password: "12321"
  db_name: "oolio-order-service-test-database"
  sslmode: "disable"
  max_conns: 10
  min_conns: 5
  conn_max_lifetime: 5m
coupon_preprocessor:
  COUPON_FILE1_URL: http://nginx-file-server:2025/file1.txt.gz
  COUPON_FILE2_URL: http://nginx-file-server:2025/file2.txt.gz
  COUPON_FILE3_URL: http://nginx-file-server:2025/file3.txt.gz
  OUTPUT_FILE_PATH: /output/processed_coupons.txt
  OUTPUT_INDEX_FILE_PATH: "/output/processed_coupons.idx"
  # COUPON_FILE1_URL: "https://orderfoodonline-files.s3.ap-southeast-2.amazonaws.com/couponbase1.gz"
  # COUPON_FILE2_URL: "https://orderfoodonline-files.s3.ap-southeast-2.amazonaws.com/couponbase2.gz"
  # COUPON_FILE3_URL: "https://orderfoodonline-files.s3.ap-southeast-2.amazonaws.com/couponbase3.gz"
redis:
  host: "localhost"
  port: 6379
  # password: ""
  db: 0
  coupon_update_channel: coupon_updates
api_keys:
  admin_api_key: ""
misc:
  should_seed_data: true