services:
  app:
    container_name: "order-service"
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ADMIN_API_KEY: ${ADMIN_API_KEY} # Or fetch from a secrets manager
      PROCESSED_COUPONS_FILE_PATH: /app/data/processed_coupons.txt
      PROCESSED_COUPONS_INDEX_FILE_PATH: /app/data/processed_coupons.idx
      NUM_HOT_COUPONS_IN_CACHE: 500000
      REDIS_COUPON_UPDATE_CHANNEL: coupon_updates
      REDIS_WORKER_TRIGGER_CHANNEL: trigger_worker
      SHOULD_SEED_DATA: true
    depends_on:
      - db
      - redis
    volumes:
      # For local development, mount source code for hot-reloading (if you set it up)
      # - .:/app
      - processed_coupons_data:/app/data

  db:
    container_name: "order-service-database"
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Expose for local DB access
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent data volume

  db-test:
    container_name: "order-service-test-database"
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${TEST_DB_PORT}
    ports:
      - "5433:5432" # Expose for local DB access

  redis:
    image: redis:6-alpine
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    configs:
      - source: redis_config
        target: /usr/local/etc/redis/redis.conf

  coupon_preprocessor:
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_COUPON_UPDATE_CHANNEL: coupon_updates
      REDIS_WORKER_TRIGGER_CHANNEL: trigger_worker
      # COUPON_FILE1_URL: https://orderfoodonline-files.s3.ap-southeast-2.amazonaws.com/couponbase1.gz
      # COUPON_FILE2_URL: https://orderfoodonline-files.s3.ap-southeast-2.amazonaws.com/couponbase2.gz
      # COUPON_FILE3_URL: https://orderfoodonline-files.s3.ap-southeast-2.amazonaws.com/couponbase3.gz
      COUPON_FILE1_URL: http://host.docker.internal:2025/couponbase1.gz
      COUPON_FILE2_URL: http://host.docker.internal:2025/couponbase2.gz
      COUPON_FILE3_URL: http://host.docker.internal:2025/couponbase3.gz
      OUTPUT_FILE_PATH: /output/processed_coupons.txt
      OUTPUT_INDEX_FILE_PATH: /output/processed_coupons.idx
      PROCESSED_COUPONS_FILE_PATH: /app/data/processed_coupons.txt
      PROCESSED_COUPONS_INDEX_FILE_PATH: /app/data/processed_coupons.idx
    depends_on:
      - redis
    volumes:
      - processed_coupons_data:/output
      - ./configs:/app/configs
    command: ["./coupon_preprocessor"]
    deploy:
      resources:
        limits:
          cpus: '4'  # Allocate 4 CPU cores
          memory: 4G # Allocate 4 GB of RAM

volumes:
  db_data:
  redis_data:
  processed_coupons_data:

configs:
  redis_config:
    file: ./redis/redis.conf