
CREATE TABLE categories (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(100) UNIQUE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE,
	deleted_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE products DROP COLUMN category;
ALTER TABLE products ADD COLUMN category_id UUID REFERENCES categories(id) ON DELETE RESTRICT;


ALTER TABLE users ADD COLUMN is_active BOOLEAN DEFAULT false;
ALTER TABLE products ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;