
DROP TABLE categories IF EXISTS;

ALTER TABLE products ADD COLUMN category VARCHAR(100);
ALTER TABLE products DROP COLUMN;


ALTER TABLE users DROP COLUMN is_active BOOLEAN;
ALTER TABLE products DROP COLUMN deleted_at TIMESTAMP WITH TIME ZONE;